version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      VIRTUTAL_HOST: blog.evyenergy.com
      VIRTUAL_HOST: 80
      LETSENCRYPT_HOST: blog.evyenergy.com
      LETSENCRYPT_EMAIL: evyenergy@gmail.com
    volumes:
      - wordpress:/var/www/html
      - ..:/htdocs/wp-content/themes

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
